(()=>{
  const $=s=>document.querySelector(s);let settings=Store.get('settings',{scene:'rain',accent:'#c98b67',mode:'dark',animations:true,clock24:false});
  window.toast=t=>{let el=$('#toast');el.textContent=t;el.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('show'),2600)};
  function clock(){let d=new Date(),h=d.getHours(),g=h<12?'Good morning':h<17?'Good afternoon':h<21?'Good evening':'Good night',format=settings.clock24?{hour:'2-digit',minute:'2-digit',hour12:false}:{hour:'numeric',minute:'2-digit'},name=Store.get('profile',{name:''}).name;$('#roomClock').textContent=d.toLocaleTimeString([],format);$('#focusClock').textContent=d.toLocaleTimeString([],format);$('#greeting').textContent=`${g.toUpperCase()}${name?', '+name.toUpperCase():''}`}
  function apply(){document.body.dataset.scene=settings.scene;document.body.style.setProperty('--accent',settings.accent);document.body.classList.toggle('light-mode',settings.mode==='light');document.body.classList.toggle('no-animations',!settings.animations);let labels={morning:['☀️','Morning glow'],rain:['☔','Rainy afternoon'],night:['☾','Midnight hush'],snow:['❄','Soft snowfall'],forest:['🌲','Forest retreat'],beach:['🌊','Ocean air'],cafe:['☕','Corner café'],cyberpunk:['✦','Neon focus']};$('#sceneIcon').textContent=labels[settings.scene][0];$('#sceneName').textContent=labels[settings.scene][1];Store.set('settings',settings)}
  function initSettings(){$('#sceneButton').onclick=()=>$('#sceneMenu').hidden=!$('#sceneMenu').hidden;document.querySelectorAll('#sceneMenu [data-scene]').forEach(b=>b.onclick=()=>{settings.scene=b.dataset.scene;apply();$('#sceneMenu').hidden=true;toast('Scene changed to '+b.textContent.trim())});$('#settingsButton').onclick=()=>$('#settingsDrawer').hidden=false;$('#closeSettings').onclick=()=>$('#settingsDrawer').hidden=true;$('#accentPicker').value=settings.accent;$('#modePicker').value=settings.mode;$('#animationToggle').checked=settings.animations;$('#clockToggle').checked=settings.clock24;$('#accentPicker').oninput=e=>{settings.accent=e.target.value;apply()};$('#modePicker').onchange=e=>{settings.mode=e.target.value;apply()};$('#animationToggle').onchange=e=>{settings.animations=e.target.checked;apply()};$('#clockToggle').onchange=e=>{settings.clock24=e.target.checked;apply();clock()};$('#resetSettings').onclick=()=>{Store.clear();location.reload()}}
  function focus(){let overlay=$('#focusOverlay');overlay.hidden=!overlay.hidden;document.body.style.overflow=overlay.hidden?'':'hidden'}
  function keys(e){if(['INPUT','TEXTAREA'].includes(document.activeElement.tagName))return;if(e.code==='Space'){e.preventDefault();Music.play()}if(e.key.toLowerCase()==='t')Timer.toggle();if(e.key.toLowerCase()==='m')Music.toggleMute();if(e.key.toLowerCase()==='f')focus();if(e.key.toLowerCase()==='n'){$('#noteArea').focus();$('#noteArea').scrollIntoView({behavior:'smooth',block:'center'})}}
  function init(){apply();clock();setInterval(clock,1000);Timer.init();Music.init();Todos.init();Notes.init();Stats.init();Weather.init();initSettings();$('#exitFocus').onclick=focus;$('#newTaskFocus').onclick=()=>$('#taskInput').focus();document.addEventListener('keydown',keys);$('#statsButton').onclick=()=>toast('Your details are saved locally and ready to grow with you.')}
  document.addEventListener('DOMContentLoaded',init)
})();
