window.Music=(()=>{
  let playing=false, muted=false, ctx, layers={}, musicGain, musicTimer, step=0, trackIndex=0, musicLevel=.45, ambient=Store.get('ambient',{rain:35,wind:0,cafe:0,fire:0,noise:0});
  const sounds=[['rain','☔','Rain'],['wind','〰','Wind'],['cafe','☕','Café'],['fire','♨','Fireplace'],['noise','◌','White noise']],$=s=>document.querySelector(s);
  function noiseSource(){let b=ctx.createBuffer(1,ctx.sampleRate*2,ctx.sampleRate),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=Math.random()*2-1;let source=ctx.createBufferSource();source.buffer=b;source.loop=true;return source}
  function makeNoise(type,filterFrequency){let source=noiseSource(),filter=ctx.createBiquadFilter(),gain=ctx.createGain();filter.type=type;filter.frequency.value=filterFrequency;gain.gain.value=0;source.connect(filter).connect(gain).connect(ctx.destination);source.start();return gain}
  function ensureAudio(){
    if(ctx){ctx.resume();return}ctx=new (window.AudioContext||window.webkitAudioContext)();
    layers.rain=makeNoise('bandpass',2600);layers.wind=makeNoise('lowpass',310);layers.noise=makeNoise('lowpass',7200);layers.fire=makeNoise('bandpass',1150);
    let cafeOsc=ctx.createOscillator(),cafeGain=ctx.createGain(),cafeFilter=ctx.createBiquadFilter();cafeOsc.type='sine';cafeOsc.frequency.value=170;cafeFilter.type='lowpass';cafeFilter.frequency.value=440;cafeGain.gain.value=0;cafeOsc.connect(cafeFilter).connect(cafeGain).connect(ctx.destination);cafeOsc.start();layers.cafe=cafeGain;
    musicGain=ctx.createGain();musicGain.gain.value=0;musicGain.connect(ctx.destination);ctx.resume();
  }
  function note(freq,start,length,level,type='triangle'){let osc=ctx.createOscillator(),gain=ctx.createGain(),filter=ctx.createBiquadFilter();osc.type=type;osc.frequency.setValueAtTime(freq,start);filter.type='lowpass';filter.frequency.value=1500;gain.gain.setValueAtTime(0,start);gain.gain.linearRampToValueAtTime(level,start+.025);gain.gain.exponentialRampToValueAtTime(.001,start+length);osc.connect(filter).connect(gain).connect(musicGain);osc.start(start);osc.stop(start+length+.04)}
  function lofiStep(){if(!playing)return;let tracks=[{melody:[220,261.63,293.66,329.63,293.66,261.63,196,220],bass:[110,110,130.81,130.81,146.83,146.83,98,98],tempo:480,tone:'triangle'},{melody:[329.63,293.66,246.94,293.66,369.99,329.63,293.66,246.94],bass:[164.81,164.81,123.47,123.47,184.99,184.99,146.83,146.83],tempo:390,tone:'sine'},{melody:[196,233.08,261.63,293.66,349.23,293.66,261.63,233.08],bass:[98,98,116.54,116.54,130.81,130.81,87.31,87.31],tempo:570,tone:'square'}],track=tracks[trackIndex],now=ctx.currentTime,n=step%8;note(track.melody[n],now,.44,.16,track.tone);if(n%2===0){note(track.bass[n],now,.6,.36,'sine');note(track.bass[n]*1.5,now,.45,.055,'sine')}if(n===0||n===4){note(track.bass[n]/2,now,.18,.22,'sine')}step++}
  function startLofi(){if(musicTimer)return;let tempos=[480,390,570];musicGain.gain.setTargetAtTime(muted?0:musicLevel*.16,ctx.currentTime,.08);lofiStep();musicTimer=setInterval(lofiStep,tempos[trackIndex])}
  function stopLofi(){clearInterval(musicTimer);musicTimer=null;if(musicGain)musicGain.gain.setTargetAtTime(0,ctx.currentTime,.06)}
  function volume(){if(!ctx)return;let duck=playing?.28:1;Object.entries(layers).forEach(([name,g])=>{let level=muted?0:(ambient[name]||0)/100;let tone=name==='rain'?.055:name==='wind'?.035:name==='cafe'?.014:name==='fire'?.035:.03;g.gain.setTargetAtTime(level*tone*duck,ctx.currentTime,.12)})}
  function render(){let m=$('#mixer');m.innerHTML=sounds.map(([id,icon,name])=>`<div class="sound-row"><button class="${ambient[id]?'active':''}" data-sound="${id}" aria-label="Toggle ${name}">${icon}</button><span>${name}</span><input data-volume="${id}" type="range" min="0" max="100" value="${ambient[id]}" aria-label="${name} volume"><output>${ambient[id]}%</output></div>`).join('');m.querySelectorAll('[data-volume]').forEach(i=>i.oninput=e=>{ensureAudio();ambient[e.target.dataset.volume]=+e.target.value;e.target.nextElementSibling.textContent=e.target.value+'%';Store.set('ambient',ambient);volume();render()});m.querySelectorAll('[data-sound]').forEach(b=>b.onclick=()=>{ensureAudio();ambient[b.dataset.sound]=ambient[b.dataset.sound]?0:35;render();Store.set('ambient',ambient);volume()})}
  function play(){ensureAudio();playing=!playing;$('.music-card').classList.toggle('playing',playing);$('#musicPlay').textContent=playing?'Ⅱ':'▶';playing?startLofi():stopLofi();volume();window.toast(playing?'Lofi is playing — ambience softened':'Lofi paused — ambience restored')}
  function preset(name){ensureAudio();let maps={rain:{rain:48,wind:12,cafe:0,fire:0,noise:0},cafe:{rain:0,wind:0,cafe:55,fire:0,noise:12},night:{rain:20,wind:20,cafe:0,fire:25,noise:0}};ambient=maps[name];render();volume();document.querySelectorAll('.preset').forEach(x=>x.classList.toggle('active',x.dataset.preset===name));Store.set('ambient',ambient);window.toast(`${name[0].toUpperCase()+name.slice(1)} ambience is playing`)}
  function init(){render();$('#musicPlay').onclick=play;$('#soundMute').onclick=()=>{ensureAudio();muted=!muted;$('#soundMute').style.color=muted?'#df8b83':'var(--text)';volume();if(musicGain)musicGain.gain.setTargetAtTime(muted?0:musicLevel*.16,ctx.currentTime,.08);window.toast(muted?'Sound muted':'Sound restored')};document.querySelectorAll('.preset').forEach(b=>b.onclick=()=>preset(b.dataset.preset));$('#musicVolume').oninput=e=>{ensureAudio();musicLevel=+e.target.value;if(musicGain)musicGain.gain.setTargetAtTime(muted?0:musicLevel*.16,ctx.currentTime,.08)};let tracks=[['Sundown sketches','Haven Radio · 01'],['A place to begin','Haven Radio · 02'],['Soft concentration','Haven Radio · 03']];function changeTrack(next){trackIndex=(trackIndex+next+tracks.length)%tracks.length;step=0;if(musicTimer){stopLofi();startLofi()}$('#trackTitle').textContent=tracks[trackIndex][0];$('#trackArtist').textContent=tracks[trackIndex][1];window.toast(`Now playing: ${tracks[trackIndex][0]}`)}$('#nextTrack').onclick=()=>changeTrack(1);$('#previousTrack').onclick=()=>changeTrack(-1);$('#shuffleTrack').onclick=()=>{changeTrack(1+Math.floor(Math.random()*2));window.toast('Playlist shuffled')}}
  return{init,play,toggleMute(){ensureAudio();muted=!muted;volume();if(musicGain)musicGain.gain.setTargetAtTime(muted?0:musicLevel*.16,ctx.currentTime,.08)}}
})();
